try {
    let a = 1 + 2;
} catch (error) {
    console.log(error);
}
